fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-ast
    - id: debug-statements
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: detect-private-key

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1.0.1
    hooks:
    - id: upgrade-type-hints
      args: [--futures=true]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.6
    hooks:
      - id: vulture

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.5
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
