name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Check formatting
    - uses: actions/checkout@v3
    - uses: RojerGS/python-black-check@master
      with:
        line-length: '80'
        path: '.'
        exclude: '(/*.html|/*.mo|/*.po|/*.png|/*.rst)'
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
    - uses: actions/checkout@v3
    - run: docker-compose -f docker/docker-compose.test.yml run api
