name: CI

on:
  push:
  pull_request:
    branches: [ "dev" ]

jobs:
  #  pre-commit:
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@v3
  #    - uses: actions/setup-python@v3
  #    - uses: pre-commit/action@v3.0.0
  tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose -f docker/docker-compose.test.yml run api
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverages/coverage.xml
